version: '3'

services:
  mongodb:
    image: mongo:6.0.6
    container_name: ${MONGO_DB_NAME}
    restart: always
    volumes:
      - catchmon:/database-data:/data/db
    ports:
      - 27017:27017

    #También se puede usar env_file: para agregar tu archivo .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: ['--auth']

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}

volumes:
  catchmon:
    external: false
    #env_file:
    #  - .env